frontend-test:
  runs-on: ubuntu-latest

  defaults:
    run:
      working-directory: Testing/Frontend

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Fix permissions
      run: chmod +x node_modules/.bin/vitest

    - name: Run frontend tests
      run: npx vitest run