name: Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Testing/Frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fix permissions
        run: chmod +x node_modules/.bin/vitest

      - name: Run tests
        run: npx vitest run